### ISSUE TITLE
not able to run

### ISSUE THREAD

**Issue by ceecer1** [jeka-kiselyov/dimeshift#2]
I am a javascript beginner. The following is the output after trying to run, went through a lot of blog posts but could not resolve.

See the following stack trace. Please help me to fix.

> dimeshift@0.0.39 start /Users/shishir/Documents/projects/ui/backbonejs/dimeshift
> node index.js

{ [Error: Cannot find module './build/Release/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/default/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/Debug/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }

/Users/shishir/Documents/projects/ui/backbonejs/dimeshift/node_modules/bluebird/js/release/async.js:48
        fn = function () { throw arg; };
                           ^
SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:3306
    at Handshake._callback (/Users/shishir/Documents/projects/ui/backbonejs/dimeshift/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:76:20)
    at Handshake.Sequence.end (/Users/shishir/Documents/projects/ui/backbonejs/dimeshift/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at Protocol.handleNetworkError (/Users/shishir/Documents/projects/ui/backbonejs/dimeshift/node_modules/mysql/lib/protocol/Protocol.js:364:14)
    at Connection._handleNetworkError (/Users/shishir/Documents/projects/ui/backbonejs/dimeshift/node_modules/mysql/lib/Connection.js:421:18)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at emitErrorNT (net.js:1255:8)
    at nextTickCallbackWith2Args (node.js:474:9)
    at process._tickDomainCallback (node.js:429:17)

npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v5.4.1
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE
npm ERR! dimeshift@0.0.39 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the dimeshift@0.0.39 start script 'node index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the dimeshift package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs dimeshift
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls dimeshift
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/shishir/Documents/projects/ui/backbonejs/dimeshift/npm-debug.log

**Comment by ceecer1** [comment]
I changed the following file of this github repo to run this app.

includes/models/index.js -> 

var options = {
  logging: false,
  host: config.host,
  dialect: config.dialect
};

Thanks for sharing such a beautiful project in github.

**Comment by jeka-kiselyov** [comment]
Thank you.

I will add more info about configuration options to readme.
